### PR TITLE
Multiple values with a shared timestamp

### PR DESCRIPTION
**Pull request by ashtul**
We got several requests for this feature
#166 #295 #333 
As we can see, the implementation is super easy. Now should consider the implications.

Much of the diff is the change of `uncompressed` to `options`.

### CODE REVIEW

**Comment by filipecosta90** [comment]
> We got several requests for this feature
> #166 #295 #333
> As we can see, the implementation is super easy. Now should consider the implications.
> 
> Much of the diff is the change of `uncompressed` to `options`.


To make usage of the mathematical concept of "function" there is the requirement that there is exactly one function value for each argument. In our case a time-series is function with respect to time, thus one value for each point in time. So if you have something that produces two different output for the same point in time, that something is -- by definition -- not a time-series.
With regards to #295 the user wants to alter history on the time-series:
```
I want to update the Values in the key for the same timestamp by using the command
```
which I believe was decided to `wont-fix` instead of a missing feature.
With regards to #166 and #333 I believe that the solution would be to increase time granularity and not breaking all math concepts behind the functions that we need to use like avg, stddev, etc... 
Imho this is a path that will break all aggregations that depend on concepts of functions and should not be added.

**Comment by ashtul** [comment]
While we do not explicitly have an identifier for each sample at the same timestamp, they can be strictly defined and differentiated by the order in which they were entered. Since we do not erase samples until their expiry, we can repeatedly respond to the query with the same results.
So just like Streams has both millisecond and sequence ids, so can we, we just don't invest the space to store it explicitly.

As for #295, if we allow storing multiple values, the user can aggregate with "LAST" and get the last "up-to-date" sample for each millisecond.

**Comment by filipecosta90** [comment]
> So just like Streams has both millisecond and sequence ids, so can we, we just don't invest the space to store it explicitly.

Streams are to be used in an AOF manner and on Streams timestamps have no extra meaning appart from order and ease of query. In a time-serie the timestamp is the X of our defined function and we need an 1-1 mapping between timestamp and value. They are two different concepts. 
IMHO this is only possible to be solved with more precision on time but that raises the question if this is really a requirement ( to have samples in a time interval lower than millisecond for a given time-serie )

**Comment by ashtul** [comment]
To sum our conversation, having multiple values per timestamp might cause future problems especially with aggregations that expect one value only. An example can be an integral over a range. Using tags on other vendors DBs isn't comparable since this data is regarded as a separate time-series.

On the other hand, this feature can be given as an optional flag so advanced users can use it where it fits. They can even choose whether to aggregate it with `TimeBucket` of 1 with average, sum, first or last, whatever is a fit for their use-case.

TBC...

**Pull request closed without merging**
