### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by ashtul**

### CODE REVIEW

**Comment by danni-m** [comment]
@ashtul thanks for finding this, `SeriesHasRule` indeed seems like a dead code.
`freeContext` should be not be deleted, if its not being used, we should use it instead of just `free`.

**Comment by ashtul** [comment]
@danni-m 
We do not use it since the context is a global instantiation and we just provide a link to it.
I would change `.createContext` to `.getContext` since we don't create anything just get a pointer to those instances.

**Comment by danni-m** [comment]
@ashtul we are creating the context:
```
void *MaxMinCreateContext() {
    MaxMinContext *context = (MaxMinContext *)malloc(sizeof(MaxMinContext));
    context->minValue = 0;
    context->maxValue = 0;
    context->isResetted = TRUE;
    return context;
}
```

We should use the specific context functions for those kind of operations, otherwise one day we will have a memory leak with a complex aggregation that has several mallocs in it.

**Comment by ashtul** [comment]
@danni-m 
We actually need them for the dynamic allocation which I have missed.I'm pretty sure we have a leak right now. Will split the PR.

**Pull request closed without merging**
