### PR TITLE
Changing redistimeseries-py to redis-py for the client

### PR DESCRIPTION
**Pull request by chayim**

### CODE REVIEW

**Comment by danni-m** [comment]
@chayim can we link for an example for using redis-py with timeseries?

**Comment by chayim** [comment]
Super reasonable ask. I'll lift something from the unit tests.

**Comment by danni-m** [comment]
@chayim ping

**Comment by chayim** [comment]
@danni-m We generally need to document **everything** in redis-py. So for now, I've linked to the examples in the test base.

I'll revisit as we write proper docs, and link accordingly. Still an improvement over what was.

**Review by danni-m — APPROVED** [review]

**Pull request merged**
