### PR TITLE
Remove deprecated grafana datasource

### PR DESCRIPTION
**Pull request by danni-m**

### CODE REVIEW

**Review by K-Jo — APPROVED** [review]

**Comment by K-Jo** [comment]
@danni-m although not sure if we need the `7.1` in the link (or even at all)

**Comment by mikhailredis** [comment]
@K-Jo I kept it initially as an addition to `SimpleJson`, I think we can remove "7.1" because of the @danni-m archived old project.
Do we need to update README as well or it's auto-generated?

**Review by ashtul — APPROVED** [review]

**Comment by K-Jo** [comment]
@mikhailredis @danni-m please remove 7.1  and also update readme

**Comment by mikhailredis** [comment]
> @mikhailredis @danni-m please remove 7.1 and also update the readme

@danni-m I don't have permission to write to your branch.

**Pull request merged**
