### PR TITLE
Fixed docker hub reference in Dockerfile

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by rafie** [comment]
@lyrixx This fix is incorrect. `redisfab` is a thing.

**Comment by lyrixx** [comment]
The last up of [redisfab/redistimeseries](https://hub.docker.com/r/redisfab/redistimeseries/tags?page=1&ordering=last_updated): 7 
month ago

**Comment by rafie** [comment]
@lyrixx `redislabs` is the formal repo, based on Debian OS. `redisfab` is a dev-centric repo that's used for platform-aware build (which was introduced recently). The latter is used in inter-module Docker compositions (such as RedisEdge and redismod).
And hey, we just encountered an issue in the `redisfab` deployment script! :-)
I hope it sheds light on our Docker repository model.

**Comment by lyrixx** [comment]
okay 👍🏼

**Pull request closed without merging**
