### PR TITLE
Support TS.DEL

### PR DESCRIPTION
**Pull request by cwr31**
how to use:
 TS.DEL key fromTimestamp toTimestamp

### CODE REVIEW

**Comment by cwr31** [comment]
#611 #603

**Comment by Curclamas** [comment]
@cwr31 @danni-m hey folks, that feature would be very valuable for us since it could help us cleaning bogus data from our database. Is there any update on when this is expected to be finished/released?
Thanks in advance!

**Comment by rivaros** [comment]
Hello,
Indeeed, would like to upvote this PR. We are using RTS for storing 20 years of stock data for about 1000+ companies and db is growing atm. Sometimes there are API-related issues that make some specific ranges of the series contain false data. We don't have the possibility to erase ranges of data, only dropping whole KEY.
It becomes even more tricky  if we cannot recreate data from external sources after that, as 20 years of data gets lost when you just need to replace 1 day.

Ideally I would vote for TS.DELRANGE feature, but even TS.DEL would be a great step forward, as we can do TS.RANGE and then delete specific ticks in for loop.

**Comment by danni-m** [comment]
@cwr31 do you have time to rebase this work on top of master? we would like to introduce this functionality in the next major version of RedisTimeSeries.

**Comment by cwr31** [comment]
> @cwr31 do you have time to rebase this work on top of master? we would like to introduce this functionality in the next major version of RedisTimeSeries.

glad to do this, I'll let you know when I'm done

**Comment by cwr31** [comment]
> @cwr31 do you have time to rebase this work on top of master? we would like to introduce this functionality in the next major version of RedisTimeSeries.

It's already done, please review it

**Comment by keptaduona** [comment]
@danni-m Hello, we've been waiting for TS.DEL for quite some time now, would it possible to release this soon?

**Review by filipecosta90 — APPROVED** [review]

**Comment by Curclamas** [comment]
@danni-m @filipecosta90 just out of curiosity: looks like this is scheduled for the 1.6 release? Is there already a tentative schedule for the release?

**Review by filipecosta90 — APPROVED** [review]

**Comment by dilonne** [comment]
Was this fixed? Still facing the same issue with the docker image

**Comment by filipecosta90** [comment]
> Was this fixed? Still facing the same issue with the docker image

@dilonne can you confirm that you're using RedisTimeSeries v1.6:
```
docker run -p 6379:6379 -it --rm redislabs/redistimeseries:latest
```

check version:
```
% redis-cli info modules
# Modules
module:name=timeseries,ver=10606,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
```

**Comment by dilonne** [comment]
I got this

module:name=timeseries,ver=10410,api=1,filters=0,usedby=[],using=[],options=[]

Guess that's version 1.4?

**Comment by filipecosta90** [comment]
> Thanks. I had version 1.4, upgraded to 1.6 and now it's working. However doing TS.RANGE key_name 0 -1 is now giving me the following error:
> 
> (error) ERR TSDB: wrong toTimestamp
> 
> Something that changed with v1.6?

Yes. https://github.com/RedisTimeSeries/RedisTimeSeries/releases/tag/v1.6.0 introduced TS.DEL, an since then further changes/fixes where made ( as visible by the versions changelog ). 
So, if possible use v1.6.x to be able to use this feature

**Pull request merged**
