### PR TITLE
Added submodule https://github.com/RedisLabsModules/readies

### PR DESCRIPTION
**Pull request by rafie**

### CODE REVIEW

**Comment by rafie** [comment]
Dockerhub build fails because it first clones the repo and pulls submodules, then checks out the PR branch, so it ends up without new submodules, and thus fails. Found not way around this but merging to master so new submodule becomes available.

**Comment by rafie** [comment]
No substantial logic changes here, just going for deps/readies as a submodule instead the embedded version we previously used.

**Comment by danni-m** [comment]
@rafie how do we handle this on other modules?

**Comment by rafie** [comment]
@danni-m This is the first module to use readies as a submodule. Gears, AI, Search, Edge will follow. The problem is the same everywhere.

**Pull request merged**
