### PR TITLE
used inttypes's macros for scanf

### PR DESCRIPTION
**Pull request by danni-m**

### CODE REVIEW

**Comment by danni-m** [comment]
@ashtul as I explained this is the standard way of handling different compilers on different machines where `long` and `long long` means different type sizes.

**Comment by ashtul** [comment]
Casting is standard. This isn't.
A simple (unsigned long long *) would silence the compiler.

**Comment by danni-m** [comment]
@ashtul i don't want to silence the compiler, i'd prefer to be compatible with any compiler and not assume long long is 64bit.

**Comment by ashtul** [comment]
@filipecosta90 @gkorland 
what do you think?

**Comment by filipecosta90** [comment]
Approved as per our conversation.

**Pull request merged**
