### PR TITLE
`SUM` duplicate sample policy

### PR DESCRIPTION
**Pull request by dpipemazo**
Hello! This PR has two independent pieces of functionality:
- `SUM` Duplicate sample policy option
- Docker build + development improvements

I started developing the code for the `SUM` duplicate policy option and found that the Docker build improvements helped for my typical dev flow. I'm happy to remove that commit from this PR if you'd like as I realize this is definitely subject to individual dev flows and opinions.

--------------------------------

**SUM Duplicate Policy**

Setting SUM as a duplicate policy will result in the value for a single time window being the sum of all data written in the time window. This is useful for high-frequency event counting that can't guarantee two samples won't be written in the same time window.

I discussed mine and my company's motivation for this feature in #492. This would be a huge win for us as a company as we're using RTS very successfully in multiple places but seeing this occasionally. Thank you for considering!

--------------------------------

**Docker build + development improvements**

- Updates .dockerignore to ignore everything by default and adds
back in files needed for build. This is configured to be decently
permissive at the moment, but will stop the .circleCI and .github
files from being added into the container along with things like
the Dockerfile, .yml files, etc.
- Updates Dockerfile to improve build-to-build caching. Previously,
dependencies were being re-installed on source code changes, this
should speed up local builds and also CI/CD builds if build caching
is being used.
- Adds docker-compose file and documentation for local development
using Docker. This is convenient as it can allow users to edit
code as they normally would, but build/test inside roughly the
production docker container. It can reduce "works on my machine" type
issues and is generally nice for people with broken installs of
python on their machine or people who don't want to change their
python configuration.
- Adds a bit of detail to testing docs

Adding the option to easily develop in a Docker container is quite useful for me as a dev as it helps me isolate the configurations needed for the various projects I work on. The goal of these changes was to make them non-invasive and parallel to the typical dev flow. One thing that did need to be updated was the improvements to the Dockerfile to improve caching, as otherwise Docker rebuilds were taking quite a while locally. The `.dockerignore` changes also aren't strictly necessary since this project is already doing a nice job using a `builder` stage and copying the contents -- this is more of a policy I've found useful for helping to keep our container sizes down that I figured I would propose. I appreciate your considering these changes and again would be happy to remove this commit from the PR as it is completely non-essential.

### CODE REVIEW

**Comment by dpipemazo** [comment]
Reverted the `.dockerignore` changes due to causing the `ci/dockercloud` tests to fail.

**Comment by dpipemazo** [comment]
@danni-m Is this something that will be considered for merge in the near future? No worries if not, just would like to understand the roadmap for adding this functionality. I'd also be happy to remove the Docker parts of this PR as well and just submit the SUM modifications for PR if it will help get it merged faster -- it's something we really need.

**Comment by danni-m** [comment]
Hi @dpipemazo, thanks for working on this!
The code looks good to me including the tests.
Can you first split the Docker work from the other changes?

We had a dilemma with with `SUM` aggregation duplicate. we do see the need to support different duplication policies, but at up to a point where it makes sense and wouldn't cause a misuse of the module that will lead to unexpected behaviour.
So we gonna merge this one but I do want to emphasize when are we going forward.

The use-cases you mentioned in the ticket (and also other asked for that in the past) are all related to how we handle "reporting" and not necessarily saving the data.
Today we (almost) don't have  a different methods to save/manipulate data and to report data.
In your case for example, you would need to probably also keep a counter of how many samples you have.
What I mean? 
When you are reporting data you usually want to aggregate to more than 1 aggregation, for example: `min`, `max` and `avg`. if you use only 1 of these you would lose possible insights on raw data.
We would like in the future to add a different commandsets that would allow you to report raw data and get multiple aggregations on the spot without having the need to do it manually by yourself.
This new feature would allow you to also choose your bucketing size and will not limit you to same timestamp aggregation.

**Comment by danni-m** [comment]
@dpipemazo I created a PR with only the SUM changes into #565

**Comment by dpipemazo** [comment]
@danni-m Thank you very much! 

I apologize for the delay here in response. I think your comment makes sense about supporting this `SUM` use case and very much appreciate your merging this feature in while you work on the new feature. I look forward to following the development!

**Pull request closed without merging**
