### PR TITLE
Fixed documentation of TS.CREATERULE (timeBucket param)

### PR DESCRIPTION
**Pull request by lyrixx**
According to my tests, the value is in seconds

### CODE REVIEW

**Comment by danni-m** [comment]
@lyrixx when you tested this did you insert your data as milliseconds or seconds?

**Comment by lyrixx** [comment]
I inserted data with seconds, like that:
```php
for ($i=1564000000; $i < 1565000000; $i++) {
    $r = $redis->rawCommand('TS.ADD', 'crawl', $i, $i);
}
```

**Comment by ashtul** [comment]
@lyrixx @danni-m 
The way you wrote it it is neither seconds nor milliseconds, it is a counter.
The other argument comes into effect only if you use the '*' automatic timestamp which will return a value in milliseconds.

**Comment by lyrixx** [comment]
I think something is strange here. A bucket does always react the same way. It depends on how you inserted data. Now, I always insert data with `*` and it's indeed in ms. 
But I wanted to bench redis before using it intensively, so I had to fake some data. And when I inserted data with a timestamp in second, all agg opération where in second.

**Comment by danni-m** [comment]
@lyrixx you always have to insert the data in milliseconds, there's no definitive way to conclude from a timestamp if its  millis or in seconds, this is way you always have to convert it to milliseconds.

**Pull request closed without merging**
