### PR TITLE
queryindex, madd, and mget edits

### PR DESCRIPTION
**Pull request by nermiller**
Updated structure, wording, and examples

### CODE REVIEW

**Review by LiorKogan — CHANGES_REQUESTED** [review]
Note for MGET:
- You accidentally deleted the complexity section

Note for QUERYINDEX 
- At least in the GitHub preview, some emoji is generated for 'telemetry:' Please verify it is not generated on the final page.

Note for MGET, QUERYINDEX, and multiple other commands:
- For filters, the wording in (uses these filters: ... where `label` equals `value`) may be misleading. It is the filtering criteria, in other words - if you'll use this filter - you'll get results only for time series that passed this filter).     Note that we have these filters also for several other commands.

**Comment by nermiller** [comment]
@LiorKogan, I changed `:office:` to `:study:` in the example and changed the filter wording. If the wording looks good to you, I'll apply it in other command pages with that wording.

**Comment by nermiller** [comment]
@LiorKogan, I incorporated your feedback and implemented further cosmetic improvements. I added collapsible headings so arguments and examples are more visible and easier to navigate.

**Comment by nermiller** [comment]
@LiorKogan, updated based on your last feedback. If ok, please merge. Thanks!

**Review by LiorKogan — CHANGES_REQUESTED** [review]
Please fix temp:TLM to temp:JLM

**Comment by nermiller** [comment]
Thanks, @LiorKogan . Will do.

**Comment by nermiller** [comment]
Updated!

**Review by LiorKogan — APPROVED** [review]

**Pull request merged**
