### PR TITLE
Spellcheck action

### PR DESCRIPTION
**Pull request by slorello89**
Adds a GitHub action to check the spelling of documents added to the docs directory, also fixes a couple of minor spelling errors. This is part of a broader effort across all the redis.io concerned repositories that I've been coordinating with @itamarhaber, similar actions have already been added to redis-doc and redis-stack-docs.

### CODE REVIEW

**Comment by gkorland** [comment]
ref https://github.com/RedisTimeSeries/RedisTimeSeries/pull/1259

**Comment by gkorland** [comment]
@LiorKogan @slorello89 I don't think this PR is still relevant, @nermiller edited all the these pages.

**Comment by nermiller** [comment]
@gkorland, this spellcheck addition is unrelated to my doc work. This is an automated feature that includes a dictionary of terms and checks spelling on all PRs as they come along. @slorello89 and @itamarhaber have already implemented it on other repos containing docs.

**Comment by gkorland** [comment]
@chayim already added a spell checker in #1259.
The question is do we need the typo fixes in this PR after your edit of the docs?

**Comment by nermiller** [comment]
@gkorland so sorry should've looked at @chayim's PR and the files. Yeah, these are older versions that I've already corrected.

**Pull request closed without merging**
