### PR TITLE
Change error message

### PR DESCRIPTION
**Pull request by gkorland**
`Update is not supported in BLOCK mode`

### CODE REVIEW

**Review by danni-m — APPROVED** [review]

**Comment by danni-m** [comment]
@gkorland failed on linting

**Review by danni-m — APPROVED** [review]

**Comment by felipecsl** [comment]
what does BLOCK mode actually mean? i've been getting this error a lot lately

**Comment by danni-m** [comment]
@felipecsl it means that you can't update previously inserted sample or insert a sample in the "past".
You can read more about it in the docs: https://oss.redislabs.com/redistimeseries/master/configuration/#duplicate_policy

**Comment by felipecsl** [comment]
ohhh `DUPLICATE_POLICY` is exactly what I was looking for, somehow I missed that configuration section. Thanks!

**Pull request merged**
