### PR TITLE
derivative aggregation

### PR DESCRIPTION
**Pull request by ashtul**
Should we change `MaxMinContext` and common functions into something like `DoubleValuesContext` similar to `SingleValueContext`?

### CODE REVIEW

**Comment by danni-m** [comment]
@ashtul we need to have a special case for the first element in the series, MinMaxContext assume `0` as the default value, which in a case of deriv would be problematic.

**Comment by ashtul** [comment]
@danni-m 
I was referring to the struct & variable names but it is good either way.
BTW, instead of having isResetted we could reset to 0.0/0.0 or `NAN` and then use `isnan()` to check.

approved?

**Comment by danni-m** [comment]
> @ashtul we need to have a special case for the first element in the series, MinMaxContext assume `0` as the default value, which in a case of deriv would be problematic.



> @danni-m
> I was referring to the struct & variable names but it is good either way.
> BTW, instead of having isResetted we could reset to 0.0/0.0 or `NAN` and then use `isnan()` to check.
> 
> approved?

just make sure the other aggregations (min/max) work with NAN as expected.

**Comment by ashtul** [comment]
The NAN staff is for future PR since it will require an rdb change with flag/version etc.

**Comment by danni-m** [comment]
@ashtul so lets use a different context for derivative.

**Comment by ashtul** [comment]
@danni-m 
This is why I wanted to use `first` and `second` as value names that can be generic.
I don't mind making a new context but it is a lot of additional redundant code for all the functions and the same thing we have for single value context, we can have for dual value context.

**Pull request closed without merging**
